from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^html/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'static'}),
    url(r'^$', 'share.index', name='index'),
    url(r'^.well-known/pki-validation/fileauth.txt', 'share.verify', name='verify'),
    #url(r'^MP_verify_IhKTFj6rjwwxC76', 'share.verify', name='verify'),
    url(r'^upload/', 'share.upload', name='upload'),
    url(r'^doupload/', 'share.doupload', name='doupload'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^taobao_hxf/$', 'taobao_hxf.views.handleRequest', name='taobao_hxf_index'),
    url(r'^taobao_hxf/subpage/(?P<pageid>\d+)/$', 'taobao_hxf.views.subpage', name='taobao_hxf_subpage'),
    url(r'^bg_xb/website/(?P<pageid>\d+)/$', 'bg_xb.views.website', name='bg_xb_website'),
    url(r'^bg_xb/forward$', 'bg_xb.views.forward'),
    url(r'^bg_xb/openimg$', 'bg_xb.views.openimg'),
    url(r'^bg_xb/memberdetail$', 'bg_xb.views.memberdetail'),
    url(r'^bg_xb/userdetail$', 'bg_xb.views.userdetail'),
    url(r'^bg_xb/articlelist$', 'bg_xb.views.articlelist'),
    url(r'^bg_xb/memberlist$', 'bg_xb.views.memberlist'),
    url(r'^bg_xb/productlist$', 'bg_xb.views.productlist'),
    url(r'^bg_xb/qalist$', 'bg_xb.views.qalist'),
    url(r'^bg_xb/userlogin$', 'bg_xb.views.userlogin'),
    url(r'^bg_xb/colmember$', 'bg_xb.views.colmember'),
    url(r'^bg_xb/colproduct$', 'bg_xb.views.colproduct'),
    url(r'^bg_xb/colmemberlist$', 'bg_xb.views.colmemberlist'),
    url(r'^bg_xb/colproductlist$', 'bg_xb.views.colproductlist'),
    url(r'^bg_xb/orderlist$', 'bg_xb.views.orderlist'),
    url(r'^bg_xb/delorder$', 'bg_xb.views.delorder'),
    url(r'^bg_xb/payable$', 'bg_xb.views.payable'),
    url(r'^bg_xb/notify$', 'bg_xb.views.notify'),
    url(r'^ebreath/getsetting$', 'ebreath.views.getsetting'),
    url(r'^ebreath/checkkd$', 'ebreath.views.checkkd'),
    url(r'^ebreath/memberdetail$', 'ebreath.views.memberdetail'),
    url(r'^ebreath/userdetail$', 'ebreath.views.userdetail'),
    url(r'^ebreath/productlist$', 'ebreath.views.productlist'),
    url(r'^ebreath/qalist$', 'ebreath.views.qalist'),
    url(r'^ebreath/userlogin$', 'ebreath.views.userlogin'),
    url(r'^ebreath/paylist$', 'ebreath.views.paylist'),
    url(r'^ebreath/orderlist$', 'ebreath.views.orderlist'),
    url(r'^ebreath/makeorder$', 'ebreath.views.makeorder'),
    url(r'^ebreath/delorder$', 'ebreath.views.delorder'),
    url(r'^ebreath/payable$', 'ebreath.views.payable'),
    url(r'^ebreath/notify$', 'ebreath.views.notify'),
    url(r'^ebreath/comment$', 'ebreath.views.comment'),
    url(r'^ebreath/getcomment$', 'ebreath.views.getcomment'),
    url(r'^xgxm/forward$', 'xgxm.views.forward'),
    url(r'^xgxm/openimg$', 'xgxm.views.openimg'),
    url(r'^xgxm/userdetail$', 'xgxm.views.userdetail'),
    url(r'^xgxm/articlelist$', 'xgxm.views.articlelist'),
    url(r'^xgxm/memberlist$', 'xgxm.views.memberlist'),
    url(r'^xgxm/productlist$', 'xgxm.views.productlist'),
    url(r'^xgxm/qalist$', 'xgxm.views.qalist'),
    url(r'^xgxm/userlogin$', 'xgxm.views.userlogin'),
    url(r'^xgxm/colproduct$', 'xgxm.views.colproduct'),
    url(r'^xgxm/colproductlist$', 'xgxm.views.colproductlist'),
    url(r'^xgxm/orderlist$', 'xgxm.views.orderlist'),
    url(r'^xgxm/delorder$', 'xgxm.views.delorder'),
    url(r'^xgxm/payable$', 'xgxm.views.payable'),
    url(r'^xgxm/notify$', 'xgxm.views.notify'),
    url(r'^lxtj/$', 'lxtj.views.handleRequest', name='lxtj_index'),
    url(r'^lxtj/category/(?P<cid>\d+)/$', 'lxtj.views.category', name='lxtj_category'),
    url(r'^lxtj/languang/$', 'lxtj.views.languang', name='lxtj_languang'),
    url(r'^lxtj/detail/(?P<cid>\d+)/(?P<vid>\d+)/$', 'lxtj.views.detail', name='lxtj_detail'),
    url(r'^lxtj/payarea/$', 'lxtj.views.payarea', name='lxtj_payarea'),
    url(r'^lxtj/payment_notify$', 'lxtj.views.payment_notify', name='lxtj_payment_notify'),
    url(r'^lxtj/getmore/(?P<type>\w+)/(?P<cid>\w+)/(?P<number>\w+)/$', 'lxtj.views.getmore', name='lxtj_getmore'),
    url(r'^lxtj/ip_refresh/$', 'lxtj.views.iprefresh', name='lxtj_iprefresh'),
    url(r'^wanda/$', 'wanda.views.handleRequest', name='wanda_index'),
    url(r'^wanda/user/(?P<userid>\w+)/$', 'wanda.views.user', name='wanda_user'),
    url(r'^wanda/notify/$', 'wanda.views.notify', name='wanda_notify'),
    url(r'^wanda/dovote/$', 'wanda.views.dovote', name='wanda_dovote'),
    url(r'^wanda/douser/$', 'wanda.views.douser', name='wanda_douser'),
    url(r'^wanda/buyticket/$', 'wanda.views.buyticket', name='wanda_buyticket'),
    url(r'^wanda/shareticket/$', 'wanda.views.shareticket', name='wanda_shareticket'),
    url(r'^wanda/sendhb/$', 'wanda.views.sendhb', name='wanda_sendhb'),
    url(r'^wanda/subpage/(?P<pageid>\d+)/$', 'wanda.views.subpage', name='wanda_subpage'),
    url(r'^wanda/(?P<userid>\w+)/(?P<pageid>\d+)/$', 'wanda.views.picturevote', name='wanda_picturevote'),
    url(r'^edu_jzs/$', 'edu_jzs.views.handleRequest', name='edu_jzs_index'),
    url(r'^edu_jzs/(?P<pageid>\d+)/$', 'edu_jzs.views.subpage', name='edu_jzs_subpage'),
    url(r'^edu_jzs/photo_(?P<pageid>\d+)/$', 'edu_jzs.views.photo', name='edu_jzs_photo'),
    url(r'^funbox/$', 'funbox.views.handleRequest', name='funbox_index'),
    url(r'^funbox/index/$', 'funbox.views.index', name='funbox_home'),
    url(r'^funbox/chargepage/$', 'funbox.views.chargepage', name='funbox_chargepage'),
    url(r'^funbox/checkdetail/$', 'funbox.views.checkdetail', name='funbox_checkdetail'),
    url(r'^funbox/pingserver/$', 'funbox.views.pingserver', name='funbox_pingserver'),
    url(r'^funbox/webhooks/$', 'funbox.views.webhooks', name='funbox_webhooks'),
    url(r'^funbox/doout/$', 'funbox.views.doout', name='funbox_doout'),
    url(r'^funbox/comment/$', 'funbox.views.comment', name='funbox_comment'),
    url(r'^funbox/docomment/$', 'funbox.views.docomment', name='funbox_docomment'),
    url(r'^funbox/dologin/$', 'funbox.views.dologin', name='funbox_dologin'),
    url(r'^funbox/doregister/$', 'funbox.views.doregister', name='funbox_doregister'),
    url(r'^funbox/userdetail/$', 'funbox.views.userdetail', name='funbox_userdetail'),
    url(r'^funbox/updateuser/$', 'funbox.views.updateuser', name='funbox_updateuser'),
    url(r'^funbox/qrcode/$', 'funbox.views.qrcode', name='funbox_qrcode'),
    url(r'^funbox/uploadimg/$', 'funbox.views.uploadimg', name='funbox_uploadimg'),
    url(r'^funbox/register/$', 'funbox.views.register', name='funbox_register'),
    url(r'^funbox/tip/$', 'funbox.views.tip', name='funbox_tip'),
    url(r'^funbox/dotip/$', 'funbox.views.dotip', name='funbox_dotip'),
    url(r'^funbox/bind/$', 'funbox.views.bind', name='funbox_bind'),
    url(r'^funbox/dobind/$', 'funbox.views.dobind', name='funbox_dobind'),
    url(r'^funbox/payable/$', 'funbox.views.payable', name='funbox_payable'),
    url(r'^funbox/payment_notify_wx/$', 'funbox.views.payment_notify_wx', name='funbox_payment_notify_wx'),
    url(r'^funbox/payment_notify_ali/$', 'funbox.views.payment_notify_ali', name='funbox_payment_notify_ali'),
    url(r'^live_hk/$', 'live_hk.views.handleRequest', name='live_hk_index'),
    url(r'^live_hk/getuserinfo/$', 'live_hk.views.getuserinfo', name='live_hk_getuserinfo'),
    url(r'^live_hk/(?P<pageid>\d+)/$', 'live_hk.views.subpage', name='live_hk_subpage'),
    url(r'^live_hk/polling/$', 'live_hk.views.polling', name='live_hk_polling'),
    url(r'^live_hk/dopoll/$', 'live_hk.views.dopoll', name='live_hk_dopoll'),
    url(r'^live_hk/getcode/$', 'live_hk.views.getcode', name='live_hk_getcode'),
    url(r'^live_hk/baoming/$', 'live_hk.views.baoming', name='live_hk_baoming'),
    url(r'^live_hk/lucky/(?P<round>\d+)/$', 'live_hk.views.lucky', name='live_hk_lucky'),
    url(r'^live_hk/sendhb/$', 'live_hk.views.sendhb', name='live_hk_sendhb'),
    url(r'^live_hk/sharewx/$', 'live_hk.views.sharewx', name='live_hk_sharewx'),
    url(r'^live_hk/showresult/(?P<type>\w+)/$', 'live_hk.views.showresult', name='live_hk_showresult'),
    url(r'^mygym/$', 'mygym.views.handleRequest', name='mygym_index'),
    url(r'^mygym/(?P<pageid>\d+)/$', 'mygym.views.subpage', name='mygym_subpage'),
    url(r'^mygym/memberinput/$', 'mygym.views.memberinput', name='mygym_memberinput'),
    url(r'^mygym/dologin/$', 'mygym.views.dologin', name='mygym_dologin'),
    url(r'^mygym/doinput/$', 'mygym.views.doinput', name='mygym_doinput'),
    url(r'^mygym/logout/$', 'mygym.views.logout', name='mygym_logout'),
    url(r'^cstv/$', 'cstv.views.videolist', name='cstv_videolist'),
    url(r'^cstv/videoplay$', 'cstv.views.videoplay', name='cstv_videoplay'),
    url(r'^zhongmi/$', 'zhongmi.views.handleRequest', name='zhongmi_index'),
    url(r'^zhongmi/customer/$', 'zhongmi.views.customer', name='zhongmi_customer'),
    url(r'^zhongmi/customerlist/$', 'zhongmi.views.customerlist', name='zhongmi_customerlist'),
    url(r'^zhongmi/inputcustomer/$', 'zhongmi.views.inputcustomer', name='zhongmi_inputcustomer'),
    url(r'^zhongmi/dologin/$', 'zhongmi.views.dologin', name='zhongmi_dologin'),
    url(r'^zhongmi/updatecustomer/$', 'zhongmi.views.updatecustomer', name='zhongmi_updatecustomer'),
    url(r'^zhongmi/buyitem/$', 'zhongmi.views.buyitem', name='zhongmi_buyitem'),
    url(r'^zhongmi/checkdetail/$', 'zhongmi.views.checkdetail', name='zhongmi_checkdetail'),
    url(r'^zhongmi/logout/$', 'zhongmi.views.logout', name='zhongmi_logout'),
    url(r'^jypay/$', 'jypay.views.handleRequest', name='jypay_index'),
    url(r'^jypay/index/(?P<cname>\w+)/$', 'jypay.views.index', name='jypay_home'),
    url(r'^jypay/query/$', 'jypay.views.query', name='jypay_query'),
    url(r'^jypay/chargepage/$', 'jypay.views.chargepage', name='jypay_chargepage'),
    url(r'^jypay/centerdetail/(?P<cname>\w+)/$', 'jypay.views.centerdetail', name='jypay_centerdetail'),
    url(r'^jypay/checkdetail/(?P<cname>\w+)/$', 'jypay.views.checkdetail', name='jypay_checkdetail'),
    url(r'^jypay/userdetail/(?P<cname>\w+)/$', 'jypay.views.userdetail', name='jypay_userdetail'),
    url(r'^jypay/doout/$', 'jypay.views.doout', name='jypay_doout'),
    url(r'^jypay/comment/$', 'jypay.views.comment', name='jypay_comment'),
    url(r'^jypay/docomment/$', 'jypay.views.docomment', name='jypay_docomment'),
    url(r'^jypay/dologin/$', 'jypay.views.dologin', name='jypay_dologin'),
    url(r'^jypay/doregister/$', 'jypay.views.doregister', name='jypay_doregister'),
    url(r'^jypay/updateuser/$', 'jypay.views.updateuser', name='jypay_updateuser'),
    url(r'^jypay/qrcode/$', 'jypay.views.qrcode', name='jypay_qrcode'),
    url(r'^jypay/uploadimg/$', 'jypay.views.uploadimg', name='jypay_uploadimg'),
    url(r'^jypay/register/(?P<cname>\w+)/$', 'jypay.views.register', name='jypay_register'),
    url(r'^jypay/tip/$', 'jypay.views.tip', name='jypay_tip'),
    url(r'^jypay/dotip/$', 'jypay.views.dotip', name='jypay_dotip'),
    url(r'^jypay/bind/(?P<cname>\w+)/$', 'jypay.views.bind', name='jypay_bind'),
    url(r'^jypay/dobind/$', 'jypay.views.dobind', name='jypay_dobind'),
    url(r'^jypay/payable/$', 'jypay.views.payable', name='jypay_payable'),
    url(r'^jypay/payment_notify_wx/$', 'jypay.views.payment_notify_wx', name='jypay_payment_notify_wx'),
    url(r'^jypay/payment_notify_ali/$', 'jypay.views.payment_notify_ali', name='jypay_payment_notify_ali'),
    url(r'^jysoft/finance/$', 'jysoft.views.finance', name='jysoft_finance'),
    url(r'^jysoft/miaochun/$', 'jysoft.views.miaochun', name='jysoft_miaochun'),
    url(r'^yukangyuan/$', 'yukangyuan.views.handleRequest', name='yukangyuan_index'),
    url(r'^yukangyuan/login/$', 'yukangyuan.views.login', name='yukangyuan_login'),
    url(r'^yukangyuan/dologin/$', 'yukangyuan.views.dologin', name='yukangyuan_dologin'),
    url(r'^yukangyuan/logout/$', 'yukangyuan.views.logout', name='yukangyuan_logout'),
    url(r'^yukangyuan/changepwd/$', 'yukangyuan.views.changepwd', name='yukangyuan_changepwd'),
    url(r'^yukangyuan/product/$', 'yukangyuan.views.product', name='yukangyuan_product'),
    url(r'^yukangyuan/addproduct/$', 'yukangyuan.views.addproduct', name='yukangyuan_addproduct'),
    url(r'^yukangyuan/customer/$', 'yukangyuan.views.customer', name='yukangyuan_customer'),
    url(r'^yukangyuan/doorder/$', 'yukangyuan.views.doorder', name='yukangyuan_doorder'),
    url(r'^yukangyuan/saler/$', 'yukangyuan.views.saler', name='yukangyuan_saler'),
    url(r'^yukangyuan/addreport/$', 'yukangyuan.views.addreport', name='yukangyuan_addreport'),
    url(r'^yukangyuan/summary/$', 'yukangyuan.views.summary', name='yukangyuan_summary'),
    url(r'^yukangyuan/getdetail/$', 'yukangyuan.views.getdetail', name='yukangyuan_getdetail'),
    url(r'^yukangyuan/deletedetail/$', 'yukangyuan.views.deletedetail', name='yukangyuan_deletedetail'),
    url(r'^yukangyuan/delorder/$', 'yukangyuan.views.delorder', name='yukangyuan_delorder'),
    url(r'^yukangyuan/dosupport/$', 'yukangyuan.views.dosupport', name='yukangyuan_dosupport'),
    url(r'^yukangyuan/doreturn/$', 'yukangyuan.views.doreturn', name='yukangyuan_doreturn'),
    url(r'^dfth/$', 'dfth.views.index', name='dfth_index'),
    url(r'^dfth/produce/$', 'dfth.views.produce', name='dfth_produce'),
    url(r'^dfth/sale/$', 'dfth.views.sale', name='dfth_sale'),
    url(r'^dfth/finance/$', 'dfth.views.finance', name='dfth_finance'),
    url(r'^dfth/purchase/$', 'dfth.views.purchase', name='dfth_purchase'),
    url(r'^dfth/dologin/$', 'dfth.views.dologin', name='dfth_dologin'),
    url(r'^dfth/logout/$', 'dfth.views.logout', name='dfth_logout'),
    url(r'^dfth/changepwd/$', 'dfth.views.changepwd', name='dfth_changepwd'),
    url(r'^dfth/addconsume/$', 'dfth.views.addconsume', name='dfth_addconsume'),
    url(r'^dfth/addproduce/$', 'dfth.views.addproduce', name='dfth_addproduce'),
    url(r'^dfth/addcustomer/$', 'dfth.views.addcustomer', name='dfth_addcustomer'),
    url(r'^dfth/addcontract/$', 'dfth.views.addcontract', name='dfth_addcontract'),
    url(r'^dfth/addsale/$', 'dfth.views.addsale', name='dfth_addsale'),
    url(r'^dfth/addpurchase/$', 'dfth.views.addpurchase', name='dfth_addpurchase'),
    url(r'^dfth/addincome/$', 'dfth.views.addincome', name='dfth_addincome'),
    url(r'^dfth/addexpense/$', 'dfth.views.addexpense', name='dfth_addexpense'),
    url(r'^dfth/addsupplyer/$', 'dfth.views.addsupplyer', name='dfth_addsupplyer'),
    url(r'^dfth/addsource/$', 'dfth.views.addsource', name='dfth_addsource'),
    url(r'^dfth/adddevice/$', 'dfth.views.adddevice', name='dfth_adddevice'),
    url(r'^dfth/approvesubmit/$', 'dfth.views.approvesubmit', name='dfth_approvesubmit'),
    url(r'^nongxin/$', 'nongxin.views.baoming', name='nongxin_baoming'),
    url(r'^nongxin/add/$', 'nongxin.views.add', name='nongxin_add'),
    # END_OF_URL
)
